export const tempData1 = {
  products: [
    {
      barcode_number: '9780140157376',
      barcode_formats: 'ISBN-10 0140157379, ISBN-13 9780140157376',
      mpn: '9780140157376',
      model: '',
      asin: '',
      title: 'Haroun and the Sea of Stories (Paperback)',
      category: 'Media > Books',
      manufacturer: 'Salman Rushdie',
      brand: 'Odyssey Editions',
      contributors: [
        {
          role: 'author',
          name: 'Rushdie, Salman',
        },
        {
          role: 'publisher',
          name: 'Penguin Books',
        },
      ],
      age_group: 'adult',
      ingredients: '',
      nutrition_facts: '',
      energy_efficiency_class: '',
      color: '',
      gender: '',
      material: '',
      pattern: '',
      format: 'EBook',
      multipack: '',
      size: '0.56 x 7.74 x 0.4125',
      length: '',
      width: '',
      height: '',
      weight: '0.4',
      release_date: '',
      description:
        'The author of The Satanic Verses returns with his most humorous and accessible novel yet. This is the story of Haroun a 12-year-old boy whose father Rashid is the greatest storyteller in a city so sad that it has forgotten its name. When the gift of gab suddenly deserts Rashid Haroun sets out on an adventure to rescue his print. A captivating fantasy novel for readers of all ages by the author of Midnight s Children and The Satanic Verses This is simply put a book for anyone who loves a good story. It s also a work of literary genius. --Stephen King Set in an exotic Eastern landscape peopled by magicians and fantastic talking animals Haroun and the Sea of Stories inhabits the same imaginative space as The Lord of the Rings The Alchemist The Arabian Nights and The Wizard of Oz. Twelve-year-old Haroun sets out on an adventure to restore his father s gift of storytelling by reviving the poisoned Sea of Stories. On the way he encounters many foes all intent on draining the sea of all its storytelling powers. In this wondrously delightful story Salman Rushdie gives us an imaginative work of extraordinary power and endearing humor that is at its heart an illumination of the necessity of storytelling in our lives.',
      features: [],
      images: ['https://images.barcodelookup.com/134/1342375-1.jpg'],
      last_update: '2023-01-12 08:38:57',
      stores: [
        {
          name: 'ThriftBooks.com',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '3.79',
          sale_price: '',
          tax: [],
          link: 'https://www.thriftbooks.com/w/haroun-and-the-sea-of-stories_salman-rushdie/254624/#isbn=0140157379',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 02:35:37',
        },
        {
          name: 'BetterWorld.com - New, Used, Rare Books & Textbooks',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '4.84',
          sale_price: '',
          tax: [
            {
              country: 'US',
              region: 'IN',
              rate: '7.00',
              tax_ship: 'no',
            },
          ],
          link: 'https://www.BetterWorldBooks.com/product/detail/9780140157376?shipto=US&curcode=USD&utm_source=CJ_feed',
          item_group_id: '',
          availability: 'in stock',
          condition: 'used',
          shipping: [
            {
              country: 'US',
              region: '',
              service: '',
              price: '0.00 USD',
            },
          ],
          last_update: '2022-10-27 20:11:59',
        },
        {
          name: 'AbeBooks',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '4.72',
          sale_price: '4.72',
          tax: [],
          link: 'https://www.abebooks.com/Haroun-Sea-Stories-Salman-Rushdie-Granta/30218550910/bd',
          item_group_id: '',
          availability: '',
          condition: 'used',
          shipping: [],
          last_update: '2022-08-09 05:49:11',
        },
        {
          name: 'BiggerBooks.com',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '5.25',
          sale_price: '',
          tax: [],
          link: 'http://www.biggerbooks.com/bk_detail.asp?isbn=9780140157376&referrer=BBCJ',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [
            {
              country: '',
              region: '',
              service: '',
              price: '4.99 USD',
            },
          ],
          last_update: '2022-10-27 21:31:31',
        },
        {
          name: 'iFlipd',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '5.00',
          sale_price: '',
          tax: [],
          link: 'https://www.iflipd.com/books/9780140157376',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 03:06:21',
        },
        {
          name: 'eCampus.com',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '5.10',
          sale_price: '',
          tax: [],
          link: 'http://www.ecampus.com/bk_detail.asp?isbn=9780140157376&referrer=CJ',
          item_group_id: '',
          availability: '',
          condition: 'new',
          shipping: [],
          last_update: '2022-08-02 12:28:43',
        },
        {
          name: 'Kidsbooks.com (US)',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '4.49',
          sale_price: '',
          tax: [],
          link: 'https://kidsbooks.com/Store/Details/9780140157376B',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2022-08-16 16:04:05',
        },
        {
          name: 'BookOutlet (US)',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '5.49',
          sale_price: '',
          tax: [],
          link: 'https://bookoutlet.com/Store/Details/9780140157376B',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 03:24:40',
        },
        {
          name: 'BookOutlet (Canada)',
          country: 'CA',
          currency: 'CAD',
          currency_symbol: '$',
          price: '8.79',
          sale_price: '',
          tax: [],
          link: 'https://bookoutlet.ca/Store/Details/9780140157376B',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2022-08-15 08:16:43',
        },
        {
          name: 'Knetbooks.com',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '10.00',
          sale_price: '',
          tax: [],
          link: 'http://www.knetbooks.com/search-results?terms=9780140157376&referrer=KBCJ',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [
            {
              country: '',
              region: '',
              service: '',
              price: '0.00 USD',
            },
          ],
          last_update: '2022-10-29 03:05:59',
        },
        {
          name: 'OnBuy.com',
          country: 'GB',
          currency: 'GBP',
          currency_symbol: '£',
          price: '10.17',
          sale_price: '',
          tax: [],
          link: 'https://www.onbuy.com/gb/general-fiction/haroun-and-the-sea-of-stories~c2680~p1440809/?exta=cjunct&stat=eyJpcCI6IjEwLjE3IiwiZHAiOjAsImxpZCI6IjI0ODY4ODAzIiwicyI6IjExIiwidCI6MTU4MTg3MjgxNCwiYm1jIjowfQ==',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 03:46:06',
        },
        {
          name: 'Barnes & Noble',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '14.40',
          sale_price: '',
          tax: [],
          link: 'https://www.barnesandnoble.com/w/haroun-and-the-sea-of-stories-salman-rushdie/1101818684?ean=9780140157376',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 03:08:29',
        },
        {
          name: 'Rakuten.com',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '13.50',
          sale_price: '',
          tax: [],
          link: 'https://www.rakuten.com/shop/bookshopeeus/product/BSNW9780140157376/?sku=BSNW9780140157376&scid=af_feed',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 02:36:15',
        },
        {
          name: 'Wordery (US)',
          country: 'GB',
          currency: 'GBP',
          currency_symbol: '£',
          price: '12.99',
          sale_price: '',
          tax: [],
          link: 'https://wordery.com/haroun-and-the-sea-of-stories-salman-rushdie-9780140157376',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [],
          last_update: '2022-10-26 04:17:21',
        },
        {
          name: 'Target',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '14.99',
          sale_price: '',
          tax: [],
          link: 'https://www.target.com/p/haroun-and-the-sea-of-stories-by-salman-rushdie-paperback/-/A-11712838&intsrc=CATF_1444',
          item_group_id: '',
          availability: '',
          condition: 'new',
          shipping: [],
          last_update: '2022-08-18 08:11:42',
        },
        {
          name: 'Thalia DE',
          country: 'EU',
          currency: 'EUR',
          currency_symbol: '€',
          price: '14.49',
          sale_price: '',
          tax: [],
          link: 'https://www.thalia.de/shop/home/artikeldetails/ID3288653.html?gkredf=MjAyMDExMjQwMw',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 05:18:42',
        },
        {
          name: 'Textbooks.com',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '16.00',
          sale_price: '16.00',
          tax: [],
          link: 'https://www.textbooks.com/Haroun-and-the-Sea-of-Stories-90-Edition/9780140157376/Salman-Rushdie.php',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2022-08-03 23:06:11',
        },
        {
          name: 'VitalSource',
          country: 'AU',
          currency: 'AUD',
          currency_symbol: '$',
          price: '16.00',
          sale_price: '',
          tax: [],
          link: 'https://www.vitalsource.com/products/haroun-and-the-sea-of-stories-salman-rushdie-v9781623730130?duration=perpetual',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [
            {
              country: 'US',
              region: '',
              service: 'digital download',
              price: '0.00 USD',
            },
          ],
          last_update: '2022-11-02 07:11:56',
        },
        {
          name: 'BOOKSAMILLION.COM',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '17.00',
          sale_price: '',
          tax: [],
          link: 'https://www.booksamillion.com/p/Haroun-Sea-Stories/Salman-Rushdie/9780140157376',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [],
          last_update: '2022-10-27 17:46:28',
        },
        {
          name: 'Walmart',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '16.30',
          sale_price: '16.30',
          tax: [],
          link: 'https://www.walmart.com/ip/Haroun-and-the-Sea-of-Stories-Paperback-9780140157376/518868',
          item_group_id: '',
          availability: '',
          condition: 'used',
          shipping: [],
          last_update: '2023-01-12 08:38:57',
        },
        {
          name: 'The Book Depository',
          country: 'GB',
          currency: 'GBP',
          currency_symbol: '£',
          price: '15.32',
          sale_price: '',
          tax: [],
          link: 'https://www.bookdepository.com/Haroun-and-the-Sea-of-Stories-Salman-Rushdie/9780140157376?redirected=true&utm_medium=Google&utm_campaign=Base1&utm_source=UK&utm_content=Haroun-and-the-Sea-of-Stories&selectCurrency=GBP&w=AFC7AU99Z3LGZRA8VTJV',
          item_group_id: '',
          availability: '',
          condition: 'new',
          shipping: [],
          last_update: '2022-10-25 11:46:43',
        },
        {
          name: 'The Book Depository (US)',
          country: 'US',
          currency: 'USD',
          currency_symbol: '$',
          price: '17.00',
          sale_price: '',
          tax: [],
          link: 'https://www.bookdepository.com/Haroun-and-the-Sea-of-Stories-Salman-Rushdie/9780140157376?redirected=true&utm_medium=Google&utm_campaign=Base1&utm_source=US&utm_content=Haroun-and-the-Sea-of-Stories&selectCurrency=USD&w=AFCCAU99Z3LGZRA8VTJ0',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [],
          last_update: '2022-10-25 11:39:32',
        },
        {
          name: 'hugendubel DE',
          country: 'EU',
          currency: 'EUR',
          currency_symbol: '€',
          price: '18.49',
          sale_price: '',
          tax: [],
          link: 'https://www.hugendubel.de/de/taschenbuch/salman_rushdie-haroun_and_the_sea_of_stories-1676844-produkt-details.html?utm_source=zxp&utm_medium=pdm&utm_campaign=pd',
          item_group_id: '',
          availability: 'in stock',
          condition: 'new',
          shipping: [],
          last_update: '2022-04-24 07:36:11',
        },
        {
          name: 'Indigo Books & Music',
          country: 'CA',
          currency: 'CAD',
          currency_symbol: '$',
          price: '23.00',
          sale_price: '',
          tax: [],
          link: 'https://www.chapters.indigo.ca/en-ca/books/product/9780140157376-item.html',
          item_group_id: '',
          availability: '',
          condition: 'new',
          shipping: [],
          last_update: '2022-08-11 15:00:47',
        },
      ],
      reviews: [],
    },
  ],
};

export const tempData2 = {
  products: [
    {
      barcode_number: '5449000131805',
      barcode_formats: 'EAN-13 5449000131805',
      mpn: '44191',
      model: '',
      asin: 'B000YW6IOQ',
      title: 'Coca-Cola Zero - Can 33cl',
      category: 'Food, Beverages & Tobacco > Beverages > Soda',
      manufacturer: 'Coca-Cola',
      brand: 'Coca-Cola',
      contributors: [],
      age_group: '',
      ingredients: '',
      nutrition_facts: '',
      energy_efficiency_class: '',
      color: '',
      gender: '',
      material: '',
      pattern: '',
      format: '',
      multipack: '',
      size: '',
      length: '2.76',
      width: '2.76',
      height: '4.72',
      weight: '1909',
      release_date: '',
      description:
        'Tree Faces The Tree Faces are the most barking mad garden accessories we?ve ever seen! Charismatic and bizarre, the Tree Faces are intree-ging to say the least! The Screaming, Smug and Grumpy Tree Faces allow you to branch out in outrageous looking garden features! Inspired by the faces you sometimes see in knots of pine, the Tree Faces are wonderfully fictitious and will give our woody friends a whole new persona! Treat your trees and give robbers the willies with these disturbingly cool Tree Faces! Nail the Tree Faces into your trees and create a weird wonderland or freaky forest! We?re predicting the Tree Faces will really grow on people ? so don?t leaf it too late and buy one today! Do you have a question about this product? Email us now About the Tree Faces The Tree Faces are fantastic facial features which you nail into your tree to give them a personality! The Tree Faces are available in three individual designs or as a pack of three ? choose from the Grumpy Tre.',
      features: [],
      images: ['https://images.barcodelookup.com/4385/43855888-1.jpg'],
      last_update: '2021-06-22 03:36:41',
      stores: [
        {
          name: 'Grainger Global Online Business',
          country: 'GB',
          currency: 'GBP',
          currency_symbol: '£',
          price: '0.00',
          sale_price: '13.99',
          tax: [],
          link: 'https://www.zoro.co.uk/shop/catering-supplies-and-appliances/soft-drinks/coke-zero-cans-330ml---pack-24/p/ZT1083075S',
          item_group_id: 'P_ZT1083075S',
          availability: 'in stock',
          condition: 'new',
          shipping: [],
          last_update: '2022-04-27 00:52:48',
        },
        {
          name: 'Auchan PRM _PT',
          country: 'EU',
          currency: 'EUR',
          currency_symbol: '€',
          price: '0.72',
          sale_price: '',
          tax: [],
          link: 'https://www.auchan.pt/pt/bebidas-e-garrafeira/refrigerantes/refrigerantes-colas/refrigerante-com-gas-coca-cola-zero-acucar-lata-0.33l/1115018.html',
          item_group_id: '',
          availability: 'in stock',
          condition: '',
          shipping: [],
          last_update: '2022-08-24 21:37:13',
        },
        {
          name: 'Bee PL',
          country: 'PL',
          currency: 'PLN',
          currency_symbol: 'zł',
          price: '3.29',
          sale_price: '',
          tax: [],
          link: 'https://www.bee.pl/coca-cola-napoj-gazowany-o-smaku-cola-zero-cukru-330-ml_p1371854.html?utm_source=awin&utm_medium=cps&utm_campaign=products_feed',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2022-08-25 00:12:06',
        },
        {
          name: 'Polski koszyk PL',
          country: 'PL',
          currency: 'PLN',
          currency_symbol: 'zł',
          price: '2.89',
          sale_price: '',
          tax: [],
          link: 'https://polskikoszyk.pl/coca-cola-zero-0-33-l.html',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2022-04-05 19:34:13',
        },
        {
          name: 'Noon - EG',
          country: 'US',
          currency: 'EGP',
          currency_symbol: null,
          price: '5.00',
          sale_price: '',
          tax: [],
          link: 'https://www.noon.com/egypt-ar/zero-calories-soft-drink-can-330ml/N14438789A/p',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2021-06-22 02:40:13',
        },
        {
          name: 'Zoro UK',
          country: 'GB',
          currency: 'GBP',
          currency_symbol: '£',
          price: '13.99',
          sale_price: '13.99',
          tax: [],
          link: 'https://www.zoro.co.uk/shop/catering-supplies-and-appliances/soft-drinks/coke-zero-cans-330ml---pack-24/p/ZT1083075S',
          item_group_id: '',
          availability: '',
          condition: 'new',
          shipping: [],
          last_update: '2022-03-30 02:38:35',
        },
        {
          name: 'Activacek.cz',
          country: 'CZ',
          currency: 'CZK',
          currency_symbol: 'Kč',
          price: '23.00',
          sale_price: '',
          tax: [],
          link: 'https://obchod.activa.cz/produkt/coca-cola-zero-kolovy-napoj-plech-0-33-l-62931/',
          item_group_id: '',
          availability: '',
          condition: 'new',
          shipping: [],
          last_update: '2022-08-16 20:01:16',
        },
        {
          name: '8earnity IT',
          country: 'EU',
          currency: 'EUR',
          currency_symbol: '€',
          price: '28.30',
          sale_price: '',
          tax: [],
          link: 'https://8earnity.com/it/bevande-bibite-e-infusioni/83507-bevanda-rinfrescante-coca-cola-zero-33-cl-pack-24-uds-5449000131805.html',
          item_group_id: '',
          availability: 'in stock',
          condition: '',
          shipping: [],
          last_update: '2022-08-24 19:19:28',
        },
      ],
      reviews: [],
    },
  ],
};

export const tempData3 = {
  carbon_footprint: 3.092626914940425,
  name: 'Food Beverage',
  manufacturer: 'COCA-COLA',
  unit: 'kg',
  country: 'gb',
  manufacturer_declared_carbon_footprint: 3.092626914940425,
  source_url: null,
  methodology: 'product_category',
  manufacturer_reported_kgco2: 3.092626914940425,
  kgco2: 3.092626914940425,
  model: 'Food Beverage',
};

export const tempData4 = [
  {
    id: '1',
    name: 'Product 1',
    carbonFootprint: 5.0,
    imageURL:
      'https://images.unsplash.com/photo-1569738287709-043a6b8f6f8a?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c3VucmlzZWFyY2h8ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80',
    quantity: 3,
  },
  {
    id: '2',
    name: 'Product 2',
    carbonFootprint: 7.5,
    imageURL:
      'https://cdn.pixabay.com/photo/2016/03/27/18/54/technology-1283624_960_720.jpg',
    quantity: 6,
  },
  {
    id: '3',
    name: 'Product 3',
    carbonFootprint: 3.2,
    imageURL:
      'https://cdn.pixabay.com/photo/2017/08/07/14/53/aircraft-2603167_960_720.jpg',
    quantity: 1,
  },
];
